// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/identify": {
            "post": {
                "description": "get the contact links of server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Show the contacts links.",
                "parameters": [
                    {
                        "description": "Contact Request Body",
                        "name": "contact",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg.ContactRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pkg.ContactResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "pkg.Contact": {
            "type": "object",
            "properties": {
                "emails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "contact@example.com"
                    ]
                },
                "phoneNumbers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "1234567890"
                    ]
                },
                "primaryContactId": {
                    "type": "integer",
                    "example": 123
                },
                "secondaryContactIds": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        456
                    ]
                }
            }
        },
        "pkg.ContactRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "contact@example.com"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "1234567890"
                }
            }
        },
        "pkg.ContactResponse": {
            "type": "object",
            "properties": {
                "contact": {
                    "$ref": "#/definitions/pkg.Contact"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "BiteSpeed API",
	Description:      "BiteSpeed Server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
